defaults:
  - _self_
  - asset: asset_teleop_g1
  - commands: commands_teleop_g1
  - control: control_teleop_g1
  - domain_rand: domain_rand_teleop_g1
  - env: env_teleop_g1
  - init_state: init_state_teleop_g1
  - motion: motion_teleop_g1
  - noise: noise_teleop_g1
  - normalization: normalization_teleop_g1
  - train: ppo_teleop_g1
  - rewards: rewards_teleop_g1
  - sim: sim_teleop_g1
  - terrain: terrain_teleop_g1
  - viewer: viewer_base_g1


project_name: "G1"
notes: "Default Notes"
exp_name: &exp_name humanoid_smpl
headless: True
seed: 1
no_log: False
test: False 
sim_device: "cuda:0"
rl_device: "cuda:0"
sim_device_id: 0
metadata: false
play: ${test}
train: True
im_dump: False
task: "g1:teleop"
load_run: ""      #resume 的load run的地方
num_envs: 2048
checkpoint: 0

joystick: False
tmp_freeze_upper: False
max_iterations: 10000
horovod: False
resume: False #resume
experiment_name: null
run_name: null
compute_device_id: 0
graphics_device_id: 0
flex: False

use_gpu: True
use_gpu_pipeline: True
subscenes: 0
slices: 0
num_threads: 0


####### Testing Configs. ########
server_mode: False
no_virtual_display: False
render_o3d: False
debug: False
follow: False
add_proj: False
real_traj: False

hydra:
  job:
    name: ${exp_name}
    env_set:
      OMP_NUM_THREADS: 1
  run:
    dir: output/h1/${exp_name}

use_wandb: False
# zsy added for esitmations
use_tensorboard: True

###### velocity estimation ########
train_velocity_estimation: False
use_velocity_estimation: False